### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by cla6shade** [ApptiveDev/apptive-19th-marico-frontend#1]
## Description

현재 여태까지 정했던 내용들을 바탕으로, vite라는 번들러를 사용하여 react-ts 개발 환경을 구축하고  tailwind 라이브러리까지 설치를 완료했습니다.

다음 사항들은 지금부터 정해야 할 것들을 기록한 것입니다.

## To-Do
- [x] 코드 스타일 통일(eslint 설정)
(google이나 airbnb 등 정형화된 가이드라인을 따르면 될 것 같습니다)
- [x] 틀 짜기
(좀 추상적이긴 한데, 내일이나 모레 구체화해서 다시 적어두겠습니다)
- [x] 커밋 메시지/브랜치 작명, 이슈 제목 등 협업을 위한 규칙 정하기

일단 생각나는대로 적어봤습니다. 혹시나 더 정해야 할 부분이 있다면 코멘트 달아주시면 감사하겠습니다. 위 리스트에 바로 수정해서 추가하도록 하겠습니다~

## ETC

- 패키지 관리자는 npm 대신 yarn을 사용 중입니다. 이것저것 알아본 결과 yarn이 npm보다 보안 면에서 더 우수하고, 패키지 설치 속도가 더 빠르다고 합니다(ref -https://youngmin.hashnode.dev/npm-yarn). 따라서 프로젝트 받아서 설치하실 때 클론하신 뒤에 프로젝트 루트 디렉터리에서 'yarn'이라는 명령어 하나만 실행해주시면 될 것 같습니다.

**Comment by KIJUNG-CHAE** [comment]
# 세형님 고생하셨습니다! 👍🏻

---
# Comment!
## 1. 코드 스타일 통일 
네 빅테크기업이 사용하는 형식 지정해주시면 해당 스타일로 따라가겠습니다.

## 2. 틀 짜기
넵 ㅎㅎ

## 3. Git Commit Rule
```
<type>: <subject>                  — 헤더
                                                  — 빈 줄
<body>                                     — 본문
                                                  — 빈 줄
<footer>                                   — 바닥 글
```

1. **제목과 본문을 빈 행으로 구분**합니다.
2. **제목을 50글자 이내**로 제한합니다.
3. 제목의 **첫 글자는 대문자**로 작성합니다.
4. 제목의 **끝에는 마침표를 넣지 않습니다.**
5. **제목은 명령형**으로, 과거형은 넣지 않습니다.
6. 본문의 **각 행은 72글자 내**로 제한합니다
7. 어떻게(How?) 보다는 ***무엇(What?) 왜(Why?)***를 설명합니다.

### Type

-   Feat: 새로운 기능을 추가
-   Fix: 버그 수정
-   Design: CSS 등 사용자 UI 디자인 변경
-   !HOTFIX: 급하게 치명적인 버그를 고쳐야하는 경우
-   Style: 코드 포맷 변경, 세미 콜론 누락, 코드 수정이 없는 경우
-   Refactor: 프로덕션 코드 리팩토링
-   Comment: 필요한 주석 추가 및 변경
-   Docs: 문서 수정
-   Test: 테스트 코드, 리펙토링 테스트 코드 추가, Production Code(실제로 사용하는 코드) 변경 없음
-   Chore: 빌드 업무 수정, 패키지 매니저 수정, 패키지 관리자 구성 등 업데이트, Production Code 변경 없음
-   Rename: 파일 혹은 폴더명을 수정하거나 옮기는 작업만인 경우
-   Remove: 파일을 삭제하는 작업만 수행한 경우

### Footer
  꼬리말은 선택 사항입니다.
  * close, closed
  * fix, fixed
  * resolve, resolved

### 커밋 메세지 예시
```
Feat: Add post modify(update) API code

사용자 요구사항으로 게시글 수정/변경 기능 추가

해결: close #123
```
(이슈를 만들고 footer를 통해 깃에서 닫거나 pr에서 닫으면 좋을 것 같습니다.)

---
## +(추가) git branch 전략

- git flow 방식을 따르되 develop 기능 개발 후 브런치에 머지할 때는 pull request를 통해 코드리뷰를 가져가도 좋을 것 같습니다! 저희가 추후 유지보수하는 게 없어서, 릴리즈랑 태그는 안해도 될 것 같은데 의견있으시면 말씀 부탁드리겠습니다. 이 외에 다른 전략도 환영입니다!
레퍼런스: [GIT 📈 깃 브랜치 전략 정리 - Github Flow / Git Flow](https://inpa.tistory.com/entry/GIT-%E2%9A%A1%EF%B8%8F-github-flow-git-flow-%F0%9F%93%88-%EB%B8%8C%EB%9E%9C%EC%B9%98-%EC%A0%84%EB%9E%B5)
- 깃 브런치 작명은 `feature/[기능이름]` 이렇게 `작업종류/작업이름` 형식으로 가져가면 어떨까요? 예: `feature/login`, `refactor/mypage` 
- pr/issue 관련 템플릿은 제가 프론트 레퍼지토리에 등록하고 말씀드리겠습니다 :)

**Comment by cla6shade** [comment]
## git branch 전략
1. 기중님 말씀대로 git-flow 방식으로 작업하면 될 것 같습니다. 저도 버전 태그나 릴리즈는 추가하지 않아도 된다고 생각합니다!
2. `develop 기능 개발 후 머지할 때는 pull request를 통해 코드리뷰를 가져간다`라는 말씀을 해주셨는데, develop branch에서 기능 개발을 완료한 후 release branch로 병합하는 PR을 생성하여 코드를 리뷰하는 방식이라고 이해했습니다. 제가 이해한 부분이 맞나요?
3. branch명은 말씀해주신대로 `작업종류/작업이름`으로 가면 좋을 것  같습니다!

## 코드 스타일 관련
코드 가이드라인은 google javascript guideline을 따르는건 어떨까요? ref: [13 Noteworthy Points from Google’s JavaScript Style Guide](https://www.freecodecamp.org/news/google-publishes-a-javascript-style-guide-here-are-some-key-lessons-1810b8ad050b/)

코멘트로 확인해주시면 eslint 설정을 바꿔서 `development/initial-setup`에 커밋해놓겠습니다. 

감사합니다!

**Comment by KIJUNG-CHAE** [comment]
## 코드 스타일 관련 
> 코드 가이드라인은 google javascript guideline을 따르는건 어떨까요?

좋습니다!
### 코드 스타일 요약 및 정리
* two spaces 사용(4spaces X)
* semicolons 필수
* 수직정렬 방식
* var대신 let 사용
* 화살표 함수 사용
* singleQuote 사용
* 줄바꿈 가이드 길이: 80
* 상수: 대문자, _로 구성

## git branch 전략
> develop 기능 개발 후 머지할 때는 pull request를 통해 코드리뷰를 가져간다라는 말씀을 해주셨는데, develop branch에서 기능 개발을 완료한 후 release branch로 병합하는 PR을 생성하여 코드를 리뷰하는 방식이라고 이해했습니다. 제가 이해한 부분이 맞나요?

조금 다른데, 릴리즈 브런치를 없애고 각 작업 브런치를 develop브런치로 pr을 생성하고 코드리뷰 후 develop에 머지하는 방식입니다:)

**Comment by cla6shade** [comment]
## git branch 전략
> 조금 다른데, 릴리즈 브런치를 없애고 각 작업 브런치를 develop브런치로 pr을 생성하고 코드리뷰 후 develop에 머지하는 방식입니다

네 알겠습니다! 현재 기획안이 release 브랜치가 필요할만큼 큰지 의구심이 들었는데 저랑 같은 생각이셨군요..ㅎㅎ
eslint 설정 바꿔서 커밋해놓겠습니다. 감사합니다
